DROP TABLE IF EXISTS TBL_EMPLOYEE;
  
CREATE TABLE TBL_EMPLOYEE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(50) DEFAULT NULL,
    designation VARCHAR(50) NULL,
    salary INT NULL,
    hire_date DATE NOT NULL,
    manager_id INT,
    dept_id INT NOT NULL
);

DROP TABLE IF EXISTS TBL_DEPARTMENT;

CREATE TABLE TBL_DEPARTMENT(
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	location VARCHAR(50) NOT NULL
);
